package org.cgiar.ccafs.ap.data.model;
// Generated Dec 21, 2015 2:42:19 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;

/**
 * CasesStudies generated by hbm2java
 */
public class CasesStudies implements java.io.Serializable {


  private Integer id;
  private int projectId;
  private String comment;
  private String title;
  private String outcomeStatement;
  private String researchOutputs;
  private String researchPatern;
  private String activities;
  private String nonResearchPartneres;
  private String outputUsers;
  private String evidenceOutcome;
  private String references;
  private String file;
  private boolean isActive;
  private Date activeSince;
  private Long createdBy;
  private Long modifiedBy;
  private String modificationJustification;

  public CasesStudies() {
  }


  public CasesStudies(int projectId, boolean isActive, Date activeSince) {
    this.projectId = projectId;
    this.isActive = isActive;
    this.activeSince = activeSince;
  }

  public CasesStudies(int projectId, String comment, String title, String outcomeStatement, String researchOutputs,
    String researchPatern, String activities, String nonResearchPartneres, String outputUsers, String evidenceOutcome,
    String references, String file, boolean isActive, Date activeSince, Long createdBy, Long modifiedBy,
    String modificationJustification) {
    this.projectId = projectId;
    this.comment = comment;
    this.title = title;
    this.outcomeStatement = outcomeStatement;
    this.researchOutputs = researchOutputs;
    this.researchPatern = researchPatern;
    this.activities = activities;
    this.nonResearchPartneres = nonResearchPartneres;
    this.outputUsers = outputUsers;
    this.evidenceOutcome = evidenceOutcome;
    this.references = references;
    this.file = file;
    this.isActive = isActive;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getOutcomeStatement() {
    return this.outcomeStatement;
  }

  public void setOutcomeStatement(String outcomeStatement) {
    this.outcomeStatement = outcomeStatement;
  }

  public String getResearchOutputs() {
    return this.researchOutputs;
  }

  public void setResearchOutputs(String researchOutputs) {
    this.researchOutputs = researchOutputs;
  }

  public String getResearchPatern() {
    return this.researchPatern;
  }

  public void setResearchPatern(String researchPatern) {
    this.researchPatern = researchPatern;
  }

  public String getActivities() {
    return this.activities;
  }

  public void setActivities(String activities) {
    this.activities = activities;
  }

  public String getNonResearchPartneres() {
    return this.nonResearchPartneres;
  }

  public void setNonResearchPartneres(String nonResearchPartneres) {
    this.nonResearchPartneres = nonResearchPartneres;
  }

  public String getOutputUsers() {
    return this.outputUsers;
  }

  public void setOutputUsers(String outputUsers) {
    this.outputUsers = outputUsers;
  }

  public String getEvidenceOutcome() {
    return this.evidenceOutcome;
  }

  public void setEvidenceOutcome(String evidenceOutcome) {
    this.evidenceOutcome = evidenceOutcome;
  }

  public String getReferences() {
    return this.references;
  }

  public void setReferences(String references) {
    this.references = references;
  }

  public String getFile() {
    return this.file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public boolean isIsActive() {
    return this.isActive;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public Long getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public Long getModifiedBy() {
    return this.modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


}

