package org.cgiar.ccafs.ap.data.model;
// Generated Jan 5, 2016 2:07:57 PM by Hibernate Tools 3.5.0.Final


/**
 * CaseStudieIndicators generated by hbm2java
 */
public class CaseStudieIndicators implements java.io.Serializable {


  private Integer id;

  private CasesStudies casesStudies;

  private int idIndicator;

  public CaseStudieIndicators() {
  }

  public CaseStudieIndicators(CasesStudies casesStudies, int idIndicator) {
    this.casesStudies = casesStudies;
    this.idIndicator = idIndicator;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CaseStudieIndicators other = (CaseStudieIndicators) obj;
    if (casesStudies == null) {
      if (other.casesStudies != null) {
        return false;
      }
    } else if (!casesStudies.equals(other.casesStudies)) {
      return false;
    }
    if (idIndicator != other.idIndicator) {
      return false;
    }
    return true;
  }

  public CasesStudies getCasesStudies() {
    return this.casesStudies;
  }

  public Integer getId() {
    return this.id;
  }

  public int getIdIndicator() {
    return this.idIndicator;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((casesStudies == null) ? 0 : casesStudies.hashCode());
    result = prime * result + idIndicator;
    return result;
  }

  public void setCasesStudies(CasesStudies casesStudies) {
    this.casesStudies = casesStudies;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setIdIndicator(int idIndicator) {
    this.idIndicator = idIndicator;
  }


}

