package org.cgiar.ccafs.ap.data.model;
// Generated Dec 15, 2015 2:47:35 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;

/**
 * CrossCuttingContribution generated by hbm2java
 */
public class CrossCuttingContribution implements java.io.Serializable {


  private Integer id;
  private int projectId;
  private String genderSocial;
  private String communicationEngagement;
  private String category;
  private String file;
  private boolean isActive;
  private Date activeSince;
  private long createdBy;
  private long modifiedBy;
  private String modificationJustification;

  public CrossCuttingContribution() {
  }


  public CrossCuttingContribution(int projectId, String genderSocial, String communicationEngagement, boolean isActive,
    Date activeSince, long createdBy, long modifiedBy, String modificationJustification) {
    this.projectId = projectId;
    this.genderSocial = genderSocial;
    this.communicationEngagement = communicationEngagement;
    this.isActive = isActive;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public CrossCuttingContribution(int projectId, String genderSocial, String communicationEngagement, String category,
    String file, boolean isActive, Date activeSince, long createdBy, long modifiedBy,
    String modificationJustification) {
    this.projectId = projectId;
    this.genderSocial = genderSocial;
    this.communicationEngagement = communicationEngagement;
    this.category = category;
    this.file = file;
    this.isActive = isActive;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public String getGenderSocial() {
    return this.genderSocial;
  }

  public void setGenderSocial(String genderSocial) {
    this.genderSocial = genderSocial;
  }

  public String getCommunicationEngagement() {
    return this.communicationEngagement;
  }

  public void setCommunicationEngagement(String communicationEngagement) {
    this.communicationEngagement = communicationEngagement;
  }

  public String getCategory() {
    return this.category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public String getFile() {
    return this.file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public boolean isIsActive() {
    return this.isActive;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public long getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(long createdBy) {
    this.createdBy = createdBy;
  }

  public long getModifiedBy() {
    return this.modifiedBy;
  }

  public void setModifiedBy(long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


}

