package org.cgiar.ccafs.ap.data.model;
// Generated Jan 15, 2016 10:52:29 AM by Hibernate Tools 4.3.1.Final


/**
 * DeliverableDataSharing generated by hbm2java
 */
public class DeliverableDataSharing implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -3925089151066305160L;
  private Integer id;
  private int deliverableId;
  private Boolean institutionalRepository;
  private String linkInstitutionalRepository;
  private Boolean ccfasHostGreater;
  private String linkCcfasHostGreater;
  private Boolean ccfasHostSmaller;

  public DeliverableDataSharing() {
  }


  public DeliverableDataSharing(int deliverableId) {
    this.deliverableId = deliverableId;
  }

  public DeliverableDataSharing(int deliverableId, Boolean institutionalRepository, String linkInstitutionalRepository,
    Boolean ccfasHostGreater, String linkCcfasHostGreater, Boolean ccfasHostSmaller) {
    this.deliverableId = deliverableId;
    this.institutionalRepository = institutionalRepository;
    this.linkInstitutionalRepository = linkInstitutionalRepository;
    this.ccfasHostGreater = ccfasHostGreater;
    this.linkCcfasHostGreater = linkCcfasHostGreater;
    this.ccfasHostSmaller = ccfasHostSmaller;
  }

  public Boolean getCcfasHostGreater() {
    return this.ccfasHostGreater;
  }

  public Boolean getCcfasHostSmaller() {
    return this.ccfasHostSmaller;
  }

  public int getDeliverableId() {
    return this.deliverableId;
  }

  public Integer getId() {
    return this.id;
  }

  public Boolean getInstitutionalRepository() {
    return this.institutionalRepository;
  }

  public String getLinkCcfasHostGreater() {
    return this.linkCcfasHostGreater;
  }

  public String getLinkInstitutionalRepository() {
    return this.linkInstitutionalRepository;
  }

  public void setCcfasHostGreater(Boolean ccfasHostGreater) {
    this.ccfasHostGreater = ccfasHostGreater;
  }

  public void setCcfasHostSmaller(Boolean ccfasHostSmaller) {
    this.ccfasHostSmaller = ccfasHostSmaller;
  }

  public void setDeliverableId(int deliverableId) {
    this.deliverableId = deliverableId;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setInstitutionalRepository(Boolean institutionalRepository) {
    this.institutionalRepository = institutionalRepository;
  }

  public void setLinkCcfasHostGreater(String linkCcfasHostGreater) {
    this.linkCcfasHostGreater = linkCcfasHostGreater;
  }

  public void setLinkInstitutionalRepository(String linkInstitutionalRepository) {
    this.linkInstitutionalRepository = linkInstitutionalRepository;
  }


}

