package org.cgiar.ccafs.ap.data.model;
// Generated Jan 29, 2016 9:29:47 AM by Hibernate Tools 4.3.1.Final


/**
 * DeliverableMetadataElements generated by hbm2java
 */
public class DeliverableMetadataElements implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -7464011413613565400L;
  private Integer id;
  private int deliverableId;
  private int elementId;
  private String elementValue;
  private MetadataElements metadataElement;


  public DeliverableMetadataElements() {
  }


  public DeliverableMetadataElements(int deliverableId, int elementId) {
    this.deliverableId = deliverableId;
    this.elementId = elementId;
  }


  public DeliverableMetadataElements(int deliverableId, int elementId, String elementValue) {
    this.deliverableId = deliverableId;
    this.elementId = elementId;
    this.elementValue = elementValue;
  }


  public int getDeliverableId() {
    return this.deliverableId;
  }

  public int getElementId() {
    return this.elementId;
  }

  public String getElementValue() {
    return this.elementValue;
  }

  public Integer getId() {
    return this.id;
  }

  public MetadataElements getMetadataElement() {
    return metadataElement;
  }

  public void setDeliverableId(int deliverableId) {
    this.deliverableId = deliverableId;
  }

  public void setElementId(int elementId) {
    this.elementId = elementId;
  }

  public void setElementValue(String elementValue) {
    this.elementValue = elementValue;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setMetadataElement(MetadataElements metadataElement) {
    this.metadataElement = metadataElement;
  }


}

