package org.cgiar.ccafs.ap.data.model;
// Generated Jan 29, 2016 9:29:47 AM by Hibernate Tools 4.3.1.Final


/**
 * MetadataElements generated by hbm2java
 */
public class MetadataElements implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 1203016220640009509L;
  private Integer id;
  private String schema;
  private String element;
  private String qualifier;
  private String econdedName;
  private String status;
  private String vocabulary;
  private String definitation;
  private String value;


  public MetadataElements() {
  }


  public MetadataElements(String schema, String element, String qualifier, String econdedName, String status,
    String vocabulary, String definitation) {
    this.schema = schema;
    this.element = element;
    this.qualifier = qualifier;
    this.econdedName = econdedName;
    this.status = status;
    this.vocabulary = vocabulary;
    this.definitation = definitation;
  }

  public String getDefinitation() {
    return this.definitation;
  }

  public String getEcondedName() {
    return this.econdedName;
  }

  public String getElement() {
    return this.element;
  }

  public Integer getId() {
    return this.id;
  }

  public String getQualifier() {
    return this.qualifier;
  }

  public String getSchema() {
    return this.schema;
  }

  public String getStatus() {
    return this.status;
  }

  public String getValue() {
    return value;
  }

  public String getVocabulary() {
    return this.vocabulary;
  }

  public void setDefinitation(String definitation) {
    this.definitation = definitation;
  }

  public void setEcondedName(String econdedName) {
    this.econdedName = econdedName;
  }

  public void setElement(String element) {
    this.element = element;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setQualifier(String qualifier) {
    this.qualifier = qualifier;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public void setVocabulary(String vocabulary) {
    this.vocabulary = vocabulary;
  }


}

