package org.cgiar.ccafs.ap.data.model;
// Generated Mar 1, 2016 11:52:05 AM by Hibernate Tools 4.3.1.Final


/**
 * OutcomeSynthesis generated by hbm2java
 */
public class OutcomeSynthesis implements java.io.Serializable {


  private Integer id;
  private int ipProgamId;
  private int year;
  private int midOutcomeId;
  private int indicadorId;
  private Double achieved;
  private String synthesisAnual;
  private String synthesisGender;
  private String discrepancy;

  public OutcomeSynthesis() {
  }


  public OutcomeSynthesis(int ipProgamId, int year, int midOutcomeId, int indicadorId) {
    this.ipProgamId = ipProgamId;
    this.year = year;
    this.midOutcomeId = midOutcomeId;
    this.indicadorId = indicadorId;
  }

  public OutcomeSynthesis(int ipProgamId, int year, int midOutcomeId, int indicadorId, Double achieved,
    String synthesisAnual, String synthesisGender, String discrepancy) {
    this.ipProgamId = ipProgamId;
    this.year = year;
    this.midOutcomeId = midOutcomeId;
    this.indicadorId = indicadorId;
    this.achieved = achieved;
    this.synthesisAnual = synthesisAnual;
    this.synthesisGender = synthesisGender;
    this.discrepancy = discrepancy;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public int getIpProgamId() {
    return this.ipProgamId;
  }

  public void setIpProgamId(int ipProgamId) {
    this.ipProgamId = ipProgamId;
  }

  public int getYear() {
    return this.year;
  }

  public void setYear(int year) {
    this.year = year;
  }

  public int getMidOutcomeId() {
    return this.midOutcomeId;
  }

  public void setMidOutcomeId(int midOutcomeId) {
    this.midOutcomeId = midOutcomeId;
  }

  public int getIndicadorId() {
    return this.indicadorId;
  }

  public void setIndicadorId(int indicadorId) {
    this.indicadorId = indicadorId;
  }

  public Double getAchieved() {
    return this.achieved;
  }

  public void setAchieved(Double achieved) {
    this.achieved = achieved;
  }

  public String getSynthesisAnual() {
    return this.synthesisAnual;
  }

  public void setSynthesisAnual(String synthesisAnual) {
    this.synthesisAnual = synthesisAnual;
  }

  public String getSynthesisGender() {
    return this.synthesisGender;
  }

  public void setSynthesisGender(String synthesisGender) {
    this.synthesisGender = synthesisGender;
  }

  public String getDiscrepancy() {
    return this.discrepancy;
  }

  public void setDiscrepancy(String discrepancy) {
    this.discrepancy = discrepancy;
  }


}

