package org.cgiar.ccafs.ap.data.model;
// Generated Dec 7, 2015 8:15:11 AM by Hibernate Tools 3.5.0.Final


/**
 * ProjectHighligthsCountry generated by hbm2java
 */
public class ProjectHighligthsCountry implements java.io.Serializable {


  private Integer id;
  private ProjectHighligths projectHighligths;
  private int idCountry;

  public ProjectHighligthsCountry() {
  }

  public ProjectHighligthsCountry(ProjectHighligths projectHighligths, int idCountry) {
    this.projectHighligths = projectHighligths;
    this.idCountry = idCountry;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ProjectHighligths getProjectHighligths() {
    return this.projectHighligths;
  }

  public void setProjectHighligths(ProjectHighligths projectHighligths) {
    this.projectHighligths = projectHighligths;
  }

  public int getIdCountry() {
    return this.idCountry;
  }

  public void setIdCountry(int idCountry) {
    this.idCountry = idCountry;
  }


}

