package org.cgiar.ccafs.ap.data.model;
// Generated Dec 7, 2015 8:15:11 AM by Hibernate Tools 3.5.0.Final


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * ProjectHighligths generated by hbm2java
 */
public class ProjectHighligths implements java.io.Serializable {


  private Integer id;
  private String title;
  private String author;
  private Date startDate;
  private String startDateText;

  private Date endDate;
  private String endDateText;


  private String photo;


  private String description;


  private String results;

  private String partners;

  private String links;
  private String keywords;
  private String subject;
  private boolean isGlobal;
  private String objectives;

  private String publisher;


  private Integer type;


  private Long year;


  private boolean isActive;


  private Long status;


  private long projectId;

  private Date activeSince;
  private long createdBy;
  private long modifiedBy;
  private String modificationJustification;
  private Set<ProjectHighligthsTypes> projectHighligthsTypeses = new HashSet<ProjectHighligthsTypes>(0);
  private Set<ProjectHighligthsCountry> projectHighligthsCountries = new HashSet<ProjectHighligthsCountry>(0);
  private List<Country> countries = new ArrayList<>();
  private List<Integer> countriesIds = new ArrayList<>();
  private List<ProjectHighlightsType> TypesIds = new ArrayList<>();
  private List<String> typesids = new ArrayList<>();

  public ProjectHighligths() {
  }

  public ProjectHighligths(int id) {
    this.id = id;
  }

  public ProjectHighligths(Integer id, String title, String author, Date startDate, String startDateText, Date endDate,
    String endDateText, String photo, String description, String results, String partners, String links,
    String keywords, String subject, Integer type, Long year, boolean isActive, Long status, long projectId,
    Date activeSince, long createdBy, long modifiedBy, String modificationJustification,
    Set<ProjectHighligthsTypes> projectHighligthsTypeses, Set<ProjectHighligthsCountry> projectHighligthsCountries,
    List<Country> countries, List<Integer> countriesIds, List<ProjectHighlightsType> typesIds, List<String> typesids2) {
    super();
    this.id = id;
    this.title = title;
    this.author = author;
    this.startDate = startDate;
    this.startDateText = startDateText;
    this.endDate = endDate;
    this.endDateText = endDateText;
    this.photo = photo;
    this.description = description;
    this.results = results;
    this.partners = partners;
    this.links = links;
    this.keywords = keywords;
    this.subject = subject;
    this.type = type;
    this.year = year;
    this.isActive = isActive;
    this.status = status;
    this.projectId = projectId;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
    this.projectHighligthsTypeses = projectHighligthsTypeses;
    this.projectHighligthsCountries = projectHighligthsCountries;
    this.countries = countries;
    this.countriesIds = countriesIds;
    TypesIds = typesIds;
    typesids = typesids2;
  }

  public ProjectHighligths(String title, String author, boolean isGlobal, int leader, boolean isActive, long projectId,
    Date activeSince, long createdBy, long modifiedBy, String modificationJustification) {
    this.title = title;
    this.author = author;
    this.isActive = isActive;
    this.projectId = projectId;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public String getAuthor() {
    return this.author;
  }

  public List<Country> getCountries() {
    return countries;
  }

  public List<Integer> getCountriesIds() {
    return countriesIds;
  }

  public long getCreatedBy() {
    return this.createdBy;
  }


  public String getDescription() {
    return this.description;
  }

  public Date getEndDate() {
    return this.endDate;
  }

  public String getEndDateText() {
    return endDateText;
  }


  public Integer getId() {
    return this.id;
  }


  public String getKeywords() {
    return this.keywords;
  }


  public String getLinks() {
    return this.links;
  }


  public String getModificationJustification() {
    return this.modificationJustification;
  }


  public long getModifiedBy() {
    return this.modifiedBy;
  }


  public String getObjectives() {
    return objectives;
  }


  public String getPartners() {
    return this.partners;
  }

  public String getPhoto() {
    return this.photo;
  }


  public Set<ProjectHighligthsCountry> getProjectHighligthsCountries() {
    return this.projectHighligthsCountries;
  }

  public Set<ProjectHighligthsTypes> getProjectHighligthsTypeses() {
    return this.projectHighligthsTypeses;
  }

  public long getProjectId() {
    return this.projectId;
  }


  public String getPublisher() {
    return publisher;
  }

  public String getResults() {
    return this.results;
  }

  public Date getStartDate() {
    return this.startDate;
  }

  public String getStartDateText() {
    return startDateText;
  }

  public Long getStatus() {
    return this.status;
  }


  public String getSubject() {
    return this.subject;
  }


  public String getTitle() {
    return this.title;
  }

  public Integer getType() {
    return this.type;
  }

  public List<String> getTypesids() {
    return typesids;
  }

  public List<ProjectHighlightsType> getTypesIds() {
    return TypesIds;
  }


  public Long getYear() {
    return this.year;
  }

  public boolean isIsActive() {
    return this.isActive;
  }

  public boolean isIsGlobal() {
    return isGlobal;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public void setCountries(List<Country> countries) {
    this.countries = countries;
  }


  public void setCountriesIds(List<Integer> countriesIds) {
    this.countriesIds = countriesIds;
  }

  public void setCreatedBy(long createdBy) {
    this.createdBy = createdBy;
  }


  public void setDescription(String description) {
    this.description = description;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  public void setEndDateText(String endDateText) {
    this.endDateText = endDateText;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  }

  public void setIsGlobal(boolean isGlobal) {
    this.isGlobal = isGlobal;
  }

  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  public void setLinks(String links) {
    this.links = links;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setObjectives(String objectives) {
    this.objectives = objectives;
  }

  public void setPartners(String partners) {
    this.partners = partners;
  }


  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public void setProjectHighligthsCountries(Set<ProjectHighligthsCountry> projectHighligthsCountries) {
    this.projectHighligthsCountries = projectHighligthsCountries;
  }

  public void setProjectHighligthsTypeses(Set<ProjectHighligthsTypes> projectHighligthsTypeses) {
    this.projectHighligthsTypeses = projectHighligthsTypeses;
  }

  public void setProjectId(long projectId) {
    this.projectId = projectId;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }


  public void setResults(String results) {
    this.results = results;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public void setStartDateText(String startDateText) {
    this.startDateText = startDateText;
  }

  public void setStatus(Long status) {
    this.status = status;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public void setTypesids(List<String> typesids) {
    this.typesids = typesids;
  }

  public void setTypesIds(List<ProjectHighlightsType> typesIds) {
    TypesIds = typesIds;
  }

  public void setYear(Long year) {
    this.year = year;
  }


}

