package org.cgiar.ccafs.ap.data.model;
// Generated Dec 7, 2015 8:15:11 AM by Hibernate Tools 3.5.0.Final


/**
 * ProjectHighligthsTypes generated by hbm2java
 */
public class ProjectHighligthsTypes implements java.io.Serializable {


  private Integer id;
  private ProjectHighligths projectHighligths;
  private int idType;

  public ProjectHighligthsTypes() {
  }

  public ProjectHighligthsTypes(ProjectHighligths projectHighligths, int idType) {
    this.projectHighligths = projectHighligths;
    this.idType = idType;
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectHighligthsTypes other = (ProjectHighligthsTypes) obj;
    if (idType != other.idType) {
      return false;
    }
    return true;
  }

  public Integer getId() {
    return this.id;
  }

  public int getIdType() {
    return this.idType;
  }


  public ProjectHighligths getProjectHighligths() {
    return this.projectHighligths;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + idType;
    return result;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setIdType(int idType) {
    this.idType = idType;
  }

  public void setProjectHighligths(ProjectHighligths projectHighligths) {
    this.projectHighligths = projectHighligths;
  }


}

