package org.cgiar.ccafs.ap.data.model;
// Generated Dec 17, 2015 11:07:06 AM by Hibernate Tools 3.5.0.Final


import java.util.Date;

/**
 * OtherContributions generated by hbm2java
 */
public class ProjecteOtherContributions implements java.io.Serializable {


  /**
   * @author Christian David Garcia Oviedo -CIAT/CCFAS
   */
  private static final long serialVersionUID = 5807703289722184780L;
  private Integer id;
  private int projectId;
  private String region;

  private String indicators;
  private String description;
  private Integer target;
  private boolean isActive;
  private Date activeSince;
  private long createdBy;
  private long modifiedBy;
  private String modificationJustification;

  public ProjecteOtherContributions() {
  }


  public ProjecteOtherContributions(int projectId, boolean isActive, Date activeSince, long createdBy, long modifiedBy,
    String modificationJustification) {
    this.projectId = projectId;
    this.isActive = isActive;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public ProjecteOtherContributions(int projectId, String region, String indicators, String description, Integer target,
    boolean isActive, Date activeSince, long createdBy, long modifiedBy, String modificationJustification) {
    this.projectId = projectId;
    this.region = region;

    this.indicators = indicators;
    this.description = description;
    this.target = target;
    this.isActive = isActive;
    this.activeSince = activeSince;
    this.createdBy = createdBy;
    this.modifiedBy = modifiedBy;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public long getCreatedBy() {
    return this.createdBy;
  }

  public String getDescription() {
    return this.description;
  }


  public Integer getId() {
    return this.id;
  }

  public String getIndicators() {
    return this.indicators;
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  public long getModifiedBy() {
    return this.modifiedBy;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public String getRegion() {
    return this.region;
  }

  public Integer getTarget() {
    return this.target;
  }

  public boolean isIsActive() {
    return this.isActive;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(long createdBy) {
    this.createdBy = createdBy;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public void setId(Integer id) {
    this.id = id;
  }

  public void setIndicators(String indicators) {
    this.indicators = indicators;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public void setTarget(Integer target) {
    this.target = target;
  }


}

