package org.cgiar.ccafs.ap.data.model;
// Generated Dec 7, 2015 8:15:11 AM by Hibernate Tools 3.5.0.Final


/**
 * ProjectHighligthsTypes generated by hbm2java
 */
public class ProjectHighligthsTypes implements java.io.Serializable {


  private Integer id;
  private ProjectHighligths projectHighligths;
  private int idType;

  public ProjectHighligthsTypes() {
  }

  public ProjectHighligthsTypes(ProjectHighligths projectHighligths, int idType) {
    this.projectHighligths = projectHighligths;
    this.idType = idType;
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ProjectHighligths getProjectHighligths() {
    return this.projectHighligths;
  }

  public void setProjectHighligths(ProjectHighligths projectHighligths) {
    this.projectHighligths = projectHighligths;
  }

  public int getIdType() {
    return this.idType;
  }

  public void setIdType(int idType) {
    this.idType = idType;
  }


}

