package org.cgiar.ccafs.ap.hibernate.model;
// Generated Dec 7, 2015 11:32:58 AM by Hibernate Tools 3.5.0.Final


/**
 * DeliverablesRanking generated by hbm2java
 */
public class DeliverablesRanking implements java.io.Serializable {


  private Integer id;
  private Long deliverableId;
  private Integer address;
  private Integer potential;
  private Integer level;
  private Integer personalPerspective;
  private Boolean processData;
  private Boolean dictionary;
  private Boolean tooldata;
  private String processDataFile;
  private String tooldataComment;
  private String fileFileName;

  public DeliverablesRanking() {
  }


  public DeliverablesRanking(Long deliverableId, Integer address, Integer potential, Integer level,
    Integer personalPerspective, Boolean processData, Boolean dictionary, Boolean tooldata, String processDataFile,
    String tooldataComment) {
    this.deliverableId = deliverableId;
    this.address = address;
    this.potential = potential;
    this.level = level;
    this.personalPerspective = personalPerspective;
    this.processData = processData;
    this.dictionary = dictionary;
    this.tooldata = tooldata;
    this.processDataFile = processDataFile;
    this.tooldataComment = tooldataComment;
  }

  public Integer getAddress() {
    return this.address;
  }

  public Long getDeliverableId() {
    return this.deliverableId;
  }

  public Boolean getDictionary() {
    return this.dictionary;
  }

  public Integer getId() {
    return this.id;
  }

  public Integer getLevel() {
    return this.level;
  }

  public Integer getPersonalPerspective() {
    return this.personalPerspective;
  }

  public Integer getPotential() {
    return this.potential;
  }

  public Boolean getProcessData() {
    return this.processData;
  }

  public String getProcessDataFile() {
    return this.processDataFile;
  }

  public Boolean getTooldata() {
    return this.tooldata;
  }

  public String getTooldataComment() {
    return this.tooldataComment;
  }

  public void setAddress(Integer address) {
    this.address = address;
  }

  public void setDeliverableId(Long deliverableId) {
    this.deliverableId = deliverableId;
  }

  public void setDictionary(Boolean dictionary) {
    this.dictionary = dictionary;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public void setPersonalPerspective(Integer personalPerspective) {
    this.personalPerspective = personalPerspective;
  }

  public void setPotential(Integer potential) {
    this.potential = potential;
  }

  public void setProcessData(Boolean processData) {
    this.processData = processData;
  }

  public void setProcessDataFile(String processDataFile) {
    this.processDataFile = processDataFile;
  }

  public void setTooldata(Boolean tooldata) {
    this.tooldata = tooldata;
  }

  public void setTooldataComment(String tooldataComment) {
    this.tooldataComment = tooldataComment;
  }


}

