package org.cgiar.ccafs.ap.hibernate.model;
// Generated Dec 2, 2015 8:36:16 AM by Hibernate Tools 3.5.0.Final


/**
 * ProjectHighligthsCountry generated by hbm2java
 */
public class ProjectHighligthsCountry implements java.io.Serializable {


  private Integer id;
  private ProjectHighligths projectHighligths;
  private int idCountry;

  public ProjectHighligthsCountry() {
  }

  public ProjectHighligthsCountry(ProjectHighligths projectHighligths, int idCountry) {
    this.projectHighligths = projectHighligths;
    this.idCountry = idCountry;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectHighligthsCountry other = (ProjectHighligthsCountry) obj;
    if (idCountry != other.idCountry) {
      return false;
    }
    if (projectHighligths == null) {
      if (other.projectHighligths != null) {
        return false;
      }
    } else if (!projectHighligths.equals(other.projectHighligths)) {
      return false;
    }
    return true;
  }

  public Integer getId() {
    return this.id;
  }

  public int getIdCountry() {
    return this.idCountry;
  }

  public ProjectHighligths getProjectHighligths() {
    return this.projectHighligths;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + idCountry;
    result = prime * result + ((projectHighligths == null) ? 0 : projectHighligths.hashCode());
    return result;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setIdCountry(int idCountry) {
    this.idCountry = idCountry;
  }

  public void setProjectHighligths(ProjectHighligths projectHighligths) {
    this.projectHighligths = projectHighligths;
  }


}

